### PR TITLE
Use `poetry` (and use `mypy`, `black`, `isort`)

### PR DESCRIPTION
**Pull request by GrandMoff100**

### CODE REVIEW

**Comment by GrandMoff100** [comment]
Once you merge this, feel free to do whatever you want with your Pipfiles

**Comment by janaSunrise** [comment]
Thank you so much for the PR, but one of the reasons I didn't use `poetry` is because of the versioning issue. Poetry provides a version field, but not `__version__`. Also, for `mypy`, I haven't used it, because pyright seems to be a better choice and I might use it later down the line, while for `black`, we're already using flake8 😁 ISort would've been a great choice!

**Comment by GrandMoff100** [comment]
Completely understandable. I personally don't use those tools but looks like you have a pretty set development routine before this PR already!

I I hope you continue to have a fun with your projects.

Happy developing.

**Comment by janaSunrise** [comment]
Thank you so much! And sorry for this.

**Pull request closed without merging**
